### ISSUE TITLE
ListTableList block 有个问题

### ISSUE THREAD

**Issue by JiakunXu** [ant-design/pro-blocks#111]
ListTableList block 有个问题：

![image](https://user-images.githubusercontent.com/2619626/67157490-511fec00-f35f-11e9-8c1d-5cf5fd0e0c74.png)

antd 3.24.0 版本起 TableProps 新增了 WithStore

![image](https://user-images.githubusercontent.com/2619626/67157500-84627b00-f35f-11e9-9a65-93182f30dd2f.png)

**Comment by leshalv** [comment]
急切的需要大佬解决，目前项目一路红

**Comment by iclae** [comment]
export interface StandardTableProps<T>
  extends Omit<
    TableProps<T>,
    'columns' | 'store' | 'checkboxPropsCache' | 'setCheckboxPropsCache'
  >

暂时用这种写法解决了，看antd到时候有什么变动

**Comment by leshalv** [comment]
> export interface StandardTableProps
> extends Omit<
> TableProps,
> 'columns' | 'store' | 'checkboxPropsCache' | 'setCheckboxPropsCache'
> 
> > 
> 
> 暂时用这种写法解决了，看antd到时候有什么变动

https://github.com/ant-design/ant-design/pull/19327 估计很快就会解决了

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design/pull/19343
