### ISSUE TITLE
Bug：pro-blocks/ListSearch/src/index.tsx

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-blocks#133]
# pro-blocks/ListSearch/src/index.tsx 有一个bug

> 当前有bug的代码
```js
const tabKey = location.pathname.replace(`${url}/`, '');
```
> 正确的代码：
```js
const tabKey = location.pathname.replace(`${url}`, '');
```

> bug原因

造成不能得到`tabActiveKey`  ，因为 `${url}/`   = `/list/application//` 多了一个`/`，就无法替换了

**Comment by kevincbec** [comment]
这里没有bug，url=match.path，这个值就是"/list/application"，后面不带"/"，你可以把这个值打印出来看看，所以这里需要加一个"/"变成`${url}/`
