### ISSUE TITLE
兼容 antd@4

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/pro-blocks#145]
antd 的 rc 版本已经发布，但是旧版本的代码无法在antd@4 中使用，所以需要是 codemo 来迁移一下。

- [x] AccountCenter @chenshuai2144 
- [x] AccountSettings @chenshuai2144 
- [x] DashboardAnalysis @chenshuai2144 
- [x] DashboardMonitor @wangxingkang
- [x] DashboardWorkplace @wangxingkang
- [x] EditorFlow @wangxingkang
- [x] EditorKoni   @qhanw
- [x] EditorMind @qhanw
- [x] EmptyPage @qhanw
- [x] Exception403 @songxuecc
- [x] Exception404 @songxuecc
- [x] Exception500 @songxuecc
- [x] FormAdvancedForm  @chenguzhen87
- [x] FormBasicForm @chenguzhen87
- [x] FormStepForm @chenguzhen87
- [x] ListBasicList @chj-damon
- [x] ListCardList @chj-damon
- [x] ListSearch @chj-damon
- [x] ListSearchApplications @chj-damon
- [x] ListSearchArticles @chj-damon
- [x] ListSearchProjects @chj-damon
- [x] ListTableList @chj-damon
- [x] ProfileAdvanced @qhanw
- [x] ProfileBasic @chenguzhen87
- [x] ResultFail @chenguzhen87
- [x] ResultSuccess @chenguzhen87
- [x] UserLogin @ShawDanon 
- [x] UserRegiste @ShawDanon 
- [x] UserRegisterResult @ShawDanon

**Comment by chenshuai2144** [comment]
操作步骤：

###  安装 codemod 
``` bash
# 通过 npx 直接运行
npx -p @ant-design/codemod-v4 antd4-codemod src

# 或者全局安装
# 使用 npm
npm i -g @ant-design/codemod-v4
# 或者使用 yarn
yarn global add @ant-design/codemod-v4

# 运行
antd4-codemod src
```
详情查看： https://next.ant.design/docs/react/migration-v4-cn 


### 具体操作

以  AccountCenter 为例。进 目录，在目录中执行 `antd4-codemod AccountCenter/src`,脚本执行完毕后 ，运行 `yarn start  AccountCenter` 查看效果。

值得注意的是 如果项目中使用了 <Icon  type={type} /> 会转化成 LegacyIcon，这里需要检查一下，如果没有强烈的需求尽量删除这个代码。

**Comment by ShawDanon** [comment]
![image](https://user-images.githubusercontent.com/9554297/72123873-b6530e80-339d-11ea-87ce-e8976a0c8a94.png)

**Comment by songxuecc** [comment]
这里！！！

**Comment by chenshuai2144** [comment]
非常感谢大家
