### ISSUE TITLE
迁移到 antd@4

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/pro-blocks#158]
所有的区块都迁移到了兼容包，接下来需要迁移到 antd@4 的实现。

- [x] AccountSettings @wangxingkang 
- [x] EditorFlow @chj-damon
- [x] EditorKoni @chj-damon
- [x] EditorMind @chj-damon
- [x] FormAdvancedForm @xiaohuoni
- [x] FormBasicForm @xiaohuoni
- [x] FormStepForm @qhanw
- [x] ListBasicList @wangxingkang 
- [x] ListSearchApplications @wangxingkang 
- [x] ListTableList @songxuecc 
- [x] UserLogin @chenshuai2144 
- [x] UserRegister  @ShawDanon 
  

目标是将项目中 @ant-design/compatible 的完删除。

## 具体操作
clone 项目，切换到 antd@4 分支

以 AccountSettings 为例。进入根目录，运行 yarn start AccountSettings 查看效果。
用新的 from 替换掉原来的 form 。

## pr
pr 需要 pr 到 antd@4 分支。

**Comment by ShawDanon** [comment]
FormBasicForm

**Comment by chenshuai2144** [comment]
非常感谢，再一次的迁移完毕

**Comment by xiaohuoni** [comment]
- [ ] ListSearchArticles @xiaohuoni

**Comment by xiaohuoni** [comment]
- [ ] ListSearchProjects @xiaohuoni
