### ISSUE TITLE
动态控制列

### ISSUE THREAD

**Issue by dayongi** [ant-design/pro-blocks#178]
我在preview中看到有这几个icon
![image](https://user-images.githubusercontent.com/41787764/73650139-6590b600-46bc-11ea-8046-4ce5a2aec196.png)

但是这里面的代码中好像并没有这部分的代码？给告知下吗？

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/73708064-42a3e780-4738-11ea-8cdc-d21b41c42e65.png)

preview里面少了一个图表，代码在这里 https://github.com/ant-design/pro-blocks/blob/bfcbd62b5939df5d29706f4fcc6ae779325aac04/ListTableList/src/index.tsx#L144

**Comment by dayongi** [comment]
感谢您的回复！还有个问题想问下您，就是table组件支持右键菜单吗？类似这种！
![image](https://user-images.githubusercontent.com/41787764/73713999-696b1980-474a-11ea-9ece-f0297c969843.png)

**Comment by xiaohuoni** [comment]
没见到过
