### ISSUE TITLE
pro-table版本过低

### ISSUE THREAD

**Issue by uliian** [ant-design/pro-blocks#184]
pro-table目前使用的是^1.0.22，但是这个版本会出现bug，因为它用到了Form.create()方法，导致程序报错：
![image](https://user-images.githubusercontent.com/3947701/74586305-403b6a80-5021-11ea-82ad-b45b93dd7eeb.png)

根据目前测试来看，是因为2月11日，`@ant-design/pro-table ` 包升级到了1.0.35，导致了不兼容问题，1.0.34并没有问题

**Comment by chenshuai2144** [comment]
已经解决了
