### ISSUE TITLE
Ant design pro 4.0 下使用umi ui 安装【模板】失败

### ISSUE THREAD

**Issue by nameJw** [ant-design/pro-blocks#218]
使用Ant design pro 4.0 搭建的简单项目，发现默认没有自带“注册页”，于是我就在项目中使用umi ui （右下角那个小球）安装【模板】下的“注册页面”，但是却安装失败。发现【模板】下的所有页面都不能安装成功，但是【区块】下的组件都能安装成功。
![image](https://user-images.githubusercontent.com/37288382/78052127-4018e380-73b1-11ea-977b-9b713495c4a3.png)

**Comment by nonevx** [comment]
umi block add ant-design-pro/analysis  例如使用此命令也无法安装模块...不知道为啥..明明官网就是这么写的...

**Comment by ms-xiaosnow** [comment]
同款失败。。。

**Comment by lpp18** [comment]
同款失败。。。

**Comment by nameJw** [comment]
> 同款失败。。。
搞了一天，搞不出来，然后自己写了，还更快。

**Comment by nameJw** [comment]
> 同款失败。。。

后来我自己写了

**Comment by nameJw** [comment]
> umi block add ant-design-pro/analysis 例如使用此命令也无法安装模块...不知道为啥..明明官网就是这么写的...

是的

**Comment by nameJw** [comment]
> 同款失败。。。

官方已经修复
https://github.com/ant-design/ant-design-pro/issues/6266

**Comment by nameJw** [comment]
> > umi block add ant-design-pro/analysis 例如使用此命令也无法安装模块...不知道为啥..明明官网就是这么写的...
> 
> 是的

umi ui 安装问题官方已经修复
https://github.com/ant-design/ant-design-pro/issues/6266

**Comment by nameJw** [comment]
> 同款失败。。。

官方已经修复
https://github.com/ant-design/ant-design-pro/issues/6266

**Comment by chenshuai2144** [comment]
@nameJw  感谢你的信息同步
