### ISSUE TITLE
全新 umi@3 架构

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/pro-blocks#230]
umi 的主分支已经切换完毕，可以开始切换 umi@3 架构

- [x] AccountCenter @likeDoMine 
- [x] AccountSettings @likeDoMine 
- [x] DashboardAnalysis @wangxingkang 
- [x] DashboardMonitor @wangxingkang 
- [x] DashboardWorkplace @wangxingkang
- [x] EditorFlow 
- [x] EditorKoni   
- [x] EditorMind 
- [x] EmptyPage @chenguzhen87 
- [x] Exception403 @chenguzhen87 
- [x] Exception404 @chenguzhen87 
- [x] Exception500 @chenguzhen87 
- [x] FormAdvancedForm   @qhanw
- [x] FormBasicForm  @qhanw
- [x] FormStepForm  @qhanw
- [x] ListBasicList  @poyiding 
- [x] ListCardList  @poyiding 
- [x] ListSearch  @brickspert 
- [x] ListSearchApplications @brickspert 
- [x] ListSearchArticles @brickspert
- [x] ListSearchProjects @brickspert
- [x] ListTableList @likeDoMine 
- [x] ProfileAdvanced @zhangyanling77
- [x] ProfileBasic @chenguzhen87 
- [x] ResultFail @zhangyanling77 
- [x] ResultSuccess @zhangyanling77 
- [x] UserLogin @chj-damon 
- [x] UserRegiste @chj-damon 
- [x] UserRegisterResult @chj-damon

**Comment by chenshuai2144** [comment]
## 目标
antd pro 升级到 umi3，所有组件升级为 hooks 写法

## 必备知识
* 熟练掌握 umi3：https://umijs.org/
* 熟练掌握 React Hooks：https://reactjs.org/docs/hooks-intro.html
* 熟练掌握 Umi Hooks：https://hooks.umijs.org/hooks/async   尤其是 useRequest

## to umi3 改造步骤
1. 去 dva
    *  删除组件中 dva 相关内容。以 `src/index.tsx` 举例：
          - 删除 [connect](https://github.com/ant-design/pro-blocks/pull/229/files#diff-b4ae54b366ea9725f764bfc3ea4d0fafL203)
          - 删除 [props 中 dva 相关数据](https://github.com/ant-design/pro-blocks/pull/229/files#diff-b4ae54b366ea9725f764bfc3ea4d0fafL74) 
          - 删除 [组件 中 dva 相关类型定义](https://github.com/ant-design/pro-blocks/pull/229/files#diff-5d537a7793e0f5aedf343cd4ca1a3b22L16)
    *  网络请求从 dva 迁移到组件中。网络请求通过 useRequet 发送，同时删除组件中 dva 相关的 `dispatch` ，`loading` 等事件，改成 useRequest 的 `run`, `loading`, `data` 等数据操作。
    * useRequest 需要从 umi 中导出。`import {useRequest} from 'umi'`。
       umi 中导出的 useRequest 需要 service 返回的 ts 类型必须为 `Promise<{data: {xxx}}>`，参考[这里](https://github.com/ant-design/pro-blocks/pull/229/files#diff-4ceeebd1a9d091227efa96cedc92f380R4)
       同时，网络请求返回的数据需要包裹一层 `data: {}`。修改 `_mock.ts` 中的接口返回数据格式。
        ```
         return res.json({
            data: xxx
          });
        ``` 
    * 删除 `src/model.tsx`

2. 所有组件从 Class 升级为 Hooks，通用的逻辑，尽量使用 Umi Hooks 封装过的 Hooks。
3. 在改造过程中会碰到 TS 类型错误，需要视情况修复。
4. 删除所有的国际化

**Comment by xiaohuoni** [comment]
4.删除所有的国际化?

是不是修改国际化的使用方式？还是直接删除？

**Comment by chenshuai2144** [comment]
直接删除 提供增加的方案好了

**Comment by xiaohuoni** [comment]
考虑一下 kiwi https://github.com/alibaba/kiwi

**Comment by qhanw** [comment]
先预定这三个：
FormAdvancedForm
FormBasicForm
FormStepForm

**Comment by zhangyanling77** [comment]
ResultFail
ResultSuccess

**Comment by poyiding** [comment]
ListBasicList
 ListCardList

**Comment by chenguzhen87** [comment]
EmptyPage
Exception403
Exception404
Exception500
ListCardList

**Comment by wangxingkang** [comment]
DashboardAnalysis 
DashboardAnalysis
DashboardWorkplace

**Comment by likeDoMine** [comment]
AccountCenter
AccountSettings
 ListTableList

**Comment by chj-damon** [comment]
DashboardAnalysis
DashboardMonitor
DashboardWorkplace

**Comment by crashsol** [comment]
nice ,看来节后有希望出V5

**Comment by likeDoMine** [comment]
EditorFlow
 EditorKoni
 EditorMind
这个三个模块只需要删除国际化，我领一下这三个

**Comment by Rhuaer** [comment]
去掉了dva，那多组件间通过数据层来更新UI的功能，打算通过什么方法来实现呢？

**Comment by chj-damon** [comment]
这个不应该在block中体现，在具体的项目里面可以有多种选择

**Comment by qhanw** [comment]
> 去掉了dva，那多组件间通过数据层来更新UI的功能，打算通过什么方法来实现呢？

数据状态不多时，可以采用 props 方式或者采用 useReducer+Context API 来处理，数据状态较多可以采用 useModel 的方式。

**Comment by Rhuaer** [comment]
> > 去掉了dva，那多组件间通过数据层来更新UI的功能，打算通过什么方法来实现呢？
> 
> 数据状态不多时，可以采用 props 方式或者采用 useReducer+Context API 来处理，数据状态较多可以采用 useModel 的方式。

我觉得 @chj-damon 的意见挺合理的。
然后 @qhanw 你提到的`useModel`，从下图的[文档](https://umijs.org/zh-CN/plugins/plugin-model#usemodel)来看，只能拿到一个默认导出方法，那如果我需要`updateUser`呢，这里不是很明白这样的设计意图

![image](https://user-images.githubusercontent.com/13702561/80311692-b32c4300-8813-11ea-8901-f4ccb2686d77.png)

**Comment by chj-damon** [comment]
```tsx
export default () => {
    const [user, setUser] = useState();

	const updateUser = async () => {
		// 你的逻辑
	}

	export {
		user,
		updateUser,
	}
}
```
@Rhuaer

**Comment by admiao** [comment]
有没有model 实例

**Comment by brickspert** [comment]
一般数据在自己组件内部处理就可以了。

如果涉及到 多组件共享，或者需要持计划的数据，要使用 `useModel` ，可以参考：https://umijs.org/plugins/plugin-model#%E4%BB%8B%E7%BB%8D

**Comment by effapp** [comment]
为什么要删除国际化？v4都有国际化的，为什么v5就不提供了？
