### ISSUE TITLE
DashboardAnalysis and DashboardMonitor mock data conflict

### ISSUE THREAD

**Issue by rosariogueli** [ant-design/pro-blocks#24]
When visiting https://preview.pro.ant.design/dashboard/analysis you can see the "Stores Sales Trend" chart is full of data. 

![image](https://user-images.githubusercontent.com/976159/59053769-11fa6e00-888a-11e9-9e73-819c737f5c0c.png)

After I install the project on localhost using the following, the data is no longer loaded: 
// Install empty project of Ant Design Pro
npm create umi
Select ant-design-pro
Select TypeScript

// Add all blocks from demo preview
npm run fetch:blocks

// run project
npm start

If you login and navigate to http://localhost:8000/dashboard/analysis no data is displayed in the same chart: 
![image](https://user-images.githubusercontent.com/976159/59053900-61d93500-888a-11e9-8cf3-ad8baa3ce2fd.png)

I've figured out that the mock api where the data should be loaded for DashboardAnalysis is being overridden by the mock data for DashboardMonitor which response doesn't contain the expected data for DashboardAnalysis of course. 

I've managed to fix this by changing the following line of code, located at src/pages/dashboard/analysis/service.tsx

![image](https://user-images.githubusercontent.com/976159/59054008-a8c72a80-888a-11e9-8799-9d1d8b18ac65.png)

.. changing it with the following line of code: 

![image](https://user-images.githubusercontent.com/976159/59054076-ce543400-888a-11e9-9d4b-fdceaf9da50a.png)

And then changing the following line of code located at src/pages/dashboard/analysis/_mock.ts

![image](https://user-images.githubusercontent.com/976159/59054186-0fe4df00-888b-11e9-9371-87697f09d925.png)

... changing it with the following line of code:

![image](https://user-images.githubusercontent.com/976159/59054241-23904580-888b-11e9-982f-1fabc8f9851b.png)

It now works as expected also on localhost:

![image](https://user-images.githubusercontent.com/976159/59054320-533f4d80-888b-11e9-81a6-8600a215982a.png)

It would be great if you guys could make sure that online version and localhost version would match also the loaded mock data as it's expected by users.

**Comment by chenshuai2144** [comment]
great job. can you give a pr?
