### ISSUE TITLE
添加block 失败

### ISSUE THREAD

**Issue by saltdg** [ant-design/pro-blocks#26]
config.ts 设置的git为：defaultGitUrl: 'https://github.com/ant-design/pro-blocks',
不管是采用官网 umi block add Workplace 
还是 umi block add ant-design-pro/Workplace
甚至： umi block add https://github.com/ant-design/pro-blocks/tree/master/DashboardWorkplace

不管哪种方式都失败： fatal: not a git repository(xxx)

绝望。。。

**Comment by afc163** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/507615/59410825-6a7ebd80-8dec-11e9-828d-73a98c1b14d8.png">

**Comment by scorscor** [comment]
一样的问题，解决了吗

**Comment by oraclexudehua** [comment]
✔ Parse url and args
⠋ Clone git repo

**Comment by saltdg** [comment]
没解决，连proview.pro.ant.design 都打不开了,突然很怀念bootstrap.

**Comment by dickeylth** [comment]
> https://preview.pro.ant.design/dashboard/analysis

为啥我这边打开的页面没有这个下载的按钮呢……

**Comment by tuo** [comment]
<img width="1440" alt="Screenshot 2019-06-23 at 23 42 18" src="https://user-images.githubusercontent.com/491610/59978592-92ea9100-9610-11e9-9d46-dce197c2dba0.png">

一个是git clone 比较慢
你可以尝试git clone pro-blocks到本地，然后修改scripts/fetch-blocks.js中替换` https://github.com/ant-design/pro-blocks/tree/master` 为本地路径 类似于`~/Documents/spikes/ant-design-pro/official/pro-blocks`

另外一个是： add每一个block,都需要npm install旗下的依赖，但是exec并不会在console打印实时的log,给你一种好像卡住不动的错觉。

你可以试试在命令行直接运行：

> ./node_modules/umi/bin/umi.js block add ~/Documents/spikes/ant-design-pro/official/pro-blocks/UserLogin --path=/user/login

<img width="1440" alt="Screenshot 2019-06-23 at 23 42 56" src="https://user-images.githubusercontent.com/491610/59978663-54090b00-9611-11e9-90ec-19618aeb68bd.png">

**Comment by huangziye** [comment]
> config.ts 设置的git为：defaultGitUrl: 'https://github.com/ant-design/pro-blocks',
> 不管是采用官网 umi block add Workplace
> 还是 umi block add ant-design-pro/Workplace
> 甚至： umi block add https://github.com/ant-design/pro-blocks/tree/master/DashboardWorkplace
> 
> 不管哪种方式都失败： fatal: not a git repository(xxx)
> 
> 绝望。。。

me too.

**Comment by niexq** [comment]
同样现象，有解决方案吗？

**Comment by niexq** [comment]
同样现象，有解决方案吗？


> <img alt="Screenshot 2019-06-23 at 23 42 18" width="1440" src="https://user-images.githubusercontent.com/491610/59978592-92ea9100-9610-11e9-9d46-dce197c2dba0.png">
> 
> 一个是git clone 比较慢
> 你可以尝试git clone pro-blocks到本地，然后修改scripts/fetch-blocks.js中替换` https://github.com/ant-design/pro-blocks/tree/master` 为本地路径 类似于`~/Documents/spikes/ant-design-pro/official/pro-blocks`
> 
> 另外一个是： add每一个block,都需要npm install旗下的依赖，但是exec并不会在console打印实时的log,给你一种好像卡住不动的错觉。
> 
> 你可以试试在命令行直接运行：
> 
> > ./node_modules/umi/bin/umi.js block add ~/Documents/spikes/ant-design-pro/official/pro-blocks/UserLogin --path=/user/login
> 
> <img alt="Screenshot 2019-06-23 at 23 42 56" width="1440" src="https://user-images.githubusercontent.com/491610/59978663-54090b00-9611-11e9-90ec-19618aeb68bd.png">

git clone https://github.com/ant-design/pro-blocks.git到本地也报错

**Comment by saltdg** [comment]
那就直接download zip 解压，现在git有些时候很慢，很痛苦。

**Comment by VeChar** [comment]
> > config.ts 设置的git为：defaultGitUrl: 'https://github.com/ant-design/pro-blocks',
> > 不管是采用官网 umi block add Workplace
> > 还是 umi block add ant-design-pro/Workplace
> > 甚至： umi block add https://github.com/ant-design/pro-blocks/tree/master/DashboardWorkplace
> > 不管哪种方式都失败： fatal: not a git repository(xxx)
> > 绝望。。。
> 
> me too.

出现这种问题目前无解吗？

**Comment by saltdg** [comment]
> > > config.ts 设置的git为：defaultGitUrl: 'https://github.com/ant-design/pro-blocks',
> > > 不管是采用官网 umi block add Workplace
> > > 还是 umi block add ant-design-pro/Workplace
> > > 甚至： umi block add https://github.com/ant-design/pro-blocks/tree/master/DashboardWorkplace
> > > 不管哪种方式都失败： fatal: not a git repository(xxx)
> > > 绝望。。。
> > 
> > 
> > me too.
> 
> 出现这种问题目前无解吗？

目前我按照楼上的解决方法，直接下载或者clone pro-blocks到本地目录 比如 e:/pro-blocks;
然后添加时直接使用本地目录 umi block add e:/pro-blocks/AccountCenter --path=/User/Center 方式进行本地添加即可。
