### ISSUE TITLE
npx umi block add UserLogin  --path=/user/login 为什么安装后都是TS

### ISSUE THREAD

**Issue by waylon-edmodo** [ant-design/pro-blocks#30]
我创建项目的时候选择的是JS。

**Comment by chenshuai2144** [comment]
区块都是 ts 的，还没有支持发布为 js

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/2554

**Comment by waylon-edmodo** [comment]
谢谢回复。 那编辑user/login的index.tsx的时候，为什么页面不会自动刷新，要重启。而编辑layout中的tsx就会自动刷新，原因是什么呢？

**Comment by chenshuai2144** [comment]
重启一下服务应该就好了 服务没有监听文件改动

**Comment by waylon-edmodo** [comment]
每次都要重启，开发好麻烦的呀。
