### ISSUE TITLE
请问pro-blocks有js版吗

### ISSUE THREAD

**Issue by GuanJdoJ** [ant-design/pro-blocks#53]
tsx文件在webstrom和vscode打开总有报错弄不掉，目前也全是用js开发，求js版

**Comment by xiaohuoni** [comment]
安装的时候带上`--js` 就可以安装js版本的

**Comment by GuanJdoJ** [comment]
> 安装的时候带上`--js` 就可以安装js版本的

能说具体点吗，我是直接拉的git代码，你说的安装是yarn install的时候吗

**Comment by GuanJdoJ** [comment]
> > 安装的时候带上`--js` 就可以安装js版本的
> 
> 能说具体点吗，我是直接拉的git代码，你说的安装是yarn install的时候吗

你说的是用npx umi block add ant-design-pro/analysis --path=your/path/here --js这种安装形式吗
