### ISSUE TITLE
GGeditor模块。如何拿到Graph呢？

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/pro-blocks#56]
如果有两个Flow的话，一个设置只读、一个设置default模式。似乎只有一个配置会生效。也就是说如果先打开只读的页面，再打开另一个界面也是只读。如何拿到graph执行销毁画布操作呢？
@chenshuai2144

**Comment by afc163** [comment]
你应该去 GGeditor 的仓库反馈和提问。

**Comment by Lind-pro** [comment]
> 你应该去 GGeditor 的仓库反馈和提问。

GGeditor仓库是js版本的吧。我看这个仓库下面的是ts版本了。
