### ISSUE TITLE
ant-design-pro 包里面的定义需要修复

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/pro-blocks#8]
ant-design-pro 包里面的定义需要修复，修复后再进行修改。
其他帮忙修改的小伙伴，注意一下。大概这周ant-design-pro 会再发一个包

**Comment by afc163** [comment]
具体是啥？

**Comment by yutingzhao1991** [comment]
V4 里面 ant-design-pro 就不需要了，用到的相关地方的处理方法：

- antd 里面有的就直接用 antd
- antd 里面没有的就直接放到对应的区块下面，由使用到它的区块去关心，就不需要再发到 ant-design-pro 里面了

**Comment by xiaohuoni** [comment]
具体是很多文件没有定义，有些定义错误。
https://github.com/ant-design/ant-design-pro/pull/3815

**Comment by xiaohuoni** [comment]
@yutingzhao1991 我觉得你说的是一个可行的方案。我本来是认为，现在的pro-blocks里面的文件是你们定义好的

**Comment by yutingzhao1991** [comment]
现在 pro-blocks 就是之前的项目 copy 过来的，里面都可以按照情况做修改 ~
